


POST http://localhost:3000/signup HTTP/1.1
content-type: application/json

{
    "username": "hijrgrgrgriji",
    "email": "newjinarggggggggggggggme@gmail.com",
    "password": "30000000"
}
###
POST http://localhost:3000/login HTTP/1.1
content-type: application/json

{
    "email": "what?@gmail.com",
    "password": "123456"
}

###

GET http://localhost:3000/test/12344 HTTP/1.1
content-type: application/json