


POST http://localhost:3000/signup HTTP/1.1
content-type: application/json

{
    "username": "fefefg@gmail.com",
    "email": "bang@gmail.com",
    "password": "123245"
}
###
POST http://localhost:3000/login HTTP/1.1
content-type: application/json

{
    "emaill": "bang@gmail.com",
    "password": "123245"
}

###

POST http://localhost:3000/addcontact/bang HTTP/1.1
content-type: application/json

{

    "name" : "fonem",
    "phone" : "555-555-1234",
    "relation": "gang"
    
}
###

POST http://localhost:3000/emergency HTTP/1.1
content-type: application/json

{
    "latitude" : "353536636636",
    "longitude" : "3633333333333"
    
}

###
POST http://localhost:3000/pushToken HTTP/1.1
content-type: application/json

{
    "token" : "9i99u9"

}

###