


POST http://localhost:3000/signup HTTP/1.1
content-type: application/json

{
    "username": "fefefg@gmail.com",
    "signInToken": "4jf4oijej",
    "pushToken" : "eifjosjfe445",
    "email": "bang@gmail.com",
    "password": "123245"
}
###
POST http://localhost:3000/login HTTP/1.1
content-type: application/json

{
    "email": "alfredo117@gmail.com",
    "longitude": "-119.7702",
    "latitude" : "36.7420"
}

###

POST http://localhost:3000/addcontact HTTP/1.1
content-type: application/json

{
    "username" : "alfredo118@gmail.com",
    "contactUsername" : "fmm",
    "phone" : "555-555-oo34",
    "relation": "gang"
    
}
###

POST http://localhost:3000/emergency HTTP/1.1
content-type: application/json

{
    "username" : "alfredo117",
    "latitude" : "353536636636",
    "longitude" : "3633333333333"
    
}

###

POST http://localhost:3000/getContacts HTTP/1.1
content-type: application/json

{
    "email" : "julianprater@mail.fresnostate.edu"

    
}

###

POST http://localhost:3000/getLocations HTTP/1.1
content-type: application/json

{
    "email" : "julianprater@mail.fresnostate.edu"

}

###

